In [3]:
import tensorflow as tf
x=tf.constant(10)
print(x)

tf.Tensor(10, shape=(), dtype=int32)


In [4]:
import tensorflow as tf
a=tf.constant(10)
b=tf.constant(20)
c=tf.add(a, b)
print(c)

tf.Tensor(30, shape=(), dtype=int32)


In [5]:
import tensorflow as tf
a=tf.constant(10)
b=tf.constant(5)
print(tf.add(a, b))
print(tf.subtract(a, b))
print(tf.multiply(a, b))
print(tf.divide(a, b))

tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float64)


In [7]:
import tensorflow as tf
x=tf.Variable(10)
print(x)
x.assign(20)
print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>


In [8]:
import tensorflow as tf
x=tf.Variable(10)
print("Before:", x)
x.assign(25)
print("After:", x)

Before: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
After: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>


In [10]:
import tensorflow as tf
x=tf.Variable(10)
x.assign_add(5)
print(x)
x.assign_sub(3)
print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=15>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=12>


In [11]:
import tensorflow as tf
a=tf.constant([10, 20, 30])
b=tf.constant([1, 2, 3])
c=tf.add(a, b)
print(c)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)


In [12]:
import tensorflow as tf
a=tf.constant([10, 20, 30])
b=tf.constant([2, 3, 4])
print(tf.multiply(a, b))

tf.Tensor([ 20  60 120], shape=(3,), dtype=int32)


In [13]:
import tensorflow as tf
x=tf.Variable([10, 20, 30])
print(x)
x.assign_add([5, 5, 5])
print(x)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([15, 25, 35], dtype=int32)>


In [14]:
import tensorflow as tf
x=tf.Variable([10, 20, 30])
x[1].assign(100)
print(x)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 10, 100,  30], dtype=int32)>


In [16]:
import tensorflow as tf
x=tf.constant([1, 2, 3, 4, 5, 6])
y=tf.reshape(x,(2, 3))
z=tf.reshape(x,(3,2))
print(y)
print(z)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [18]:
import tensorflow as tf
x = tf.constant([[1, 2, 3],[4, 5, 6]])
print("Shape:",x.shape)
print("Number of dimensions:",x.ndim)
print("Data type:",x.dtype)

Shape: (2, 3)
Number of dimensions: 2
Data type: <dtype: 'int32'>


In [19]:
import tensorflow as tf
x=tf.constant([1, 2, 3],dtype=tf.float32)
print(x)
print("dtype:",x.dtype)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
dtype: <dtype: 'float32'>


In [20]:
import tensorflow as tf
a=tf.constant([1, 2, 3],dtype=tf.int32)
b=tf.constant([1.5, 2.5, 3.5],dtype=tf.float32)
print(a.dtype)
print(b.dtype)

<dtype: 'int32'>
<dtype: 'float32'>


In [21]:
import tensorflow as tf
x=tf.constant([1, 2, 3])
print("Before:",x)
print("Before dtype:",x.dtype)
y=tf.cast(x,dtype=tf.float32)
print("After:", y)
print("After dtype:", y.dtype)

Before: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Before dtype: <dtype: 'int32'>
After: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
After dtype: <dtype: 'float32'>


In [22]:
x=tf.constant([1.2, 2.8, 3.9])
y=tf.cast(x,tf.int32)
print(y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [24]:
import tensorflow as tf
a=tf.constant([10,20,30])
b=tf.constant([2,4,5])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)

Addition: tf.Tensor([12 24 35], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([ 8 16 25], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([ 20  80 150], shape=(3,), dtype=int32)
Division: tf.Tensor([5. 5. 6.], shape=(3,), dtype=float64)


In [25]:
import tensorflow as tf
a=tf.constant([10,20,30])
b=tf.constant([2,4,5])
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))

tf.Tensor([12 24 35], shape=(3,), dtype=int32)
tf.Tensor([ 8 16 25], shape=(3,), dtype=int32)
tf.Tensor([ 20  80 150], shape=(3,), dtype=int32)
tf.Tensor([5. 5. 6.], shape=(3,), dtype=float64)


In [27]:
import tensorflow as tf
x=tf.constant([1.0,2.0,3.0,4.0])
print("Square:",tf.math.square(x))
print("Square root:",tf.math.sqrt(x))
print("Exponential:",tf.math.exp(x))
print("Logarithm:",tf.math.log(x))

Square: tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)
Square root: tf.Tensor([1.        1.4142135 1.7320508 2.       ], shape=(4,), dtype=float32)
Exponential: tf.Tensor([ 2.7182817  7.389056  20.085537  54.59815  ], shape=(4,), dtype=float32)
Logarithm: tf.Tensor([0.        0.6931472 1.0986123 1.3862944], shape=(4,), dtype=float32)


In [28]:
import tensorflow as tf
x=tf.constant([-3.0,-2.0,2.0,3.0])
print("Absolute:",tf.math.abs(x))
print("Maximum:",tf.math.maximum(x,0))
print("Minimum:",tf.math.minimum(x,0))

Absolute: tf.Tensor([3. 2. 2. 3.], shape=(4,), dtype=float32)
Maximum: tf.Tensor([0. 0. 2. 3.], shape=(4,), dtype=float32)
Minimum: tf.Tensor([-3. -2.  0.  0.], shape=(4,), dtype=float32)


In [29]:
import tensorflow as tf
x=tf.constant([10.0,20.0,30.0,40.0])
print("Sum:",tf.reduce_sum(x))
print("Mean:",tf.reduce_mean(x))
print("Maximum:",tf.reduce_max(x))
print("Minimum:",tf.reduce_min(x))

Sum: tf.Tensor(100.0, shape=(), dtype=float32)
Mean: tf.Tensor(25.0, shape=(), dtype=float32)
Maximum: tf.Tensor(40.0, shape=(), dtype=float32)
Minimum: tf.Tensor(10.0, shape=(), dtype=float32)


In [34]:
x=tf.constant([[10,20,30],[40,50,60]])
print(x)
print(tf.reduce_sum(x))
print(tf.reduce_sum(x, axis=1))
print(tf.reduce_sum(x, axis=0))

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(210, shape=(), dtype=int32)
tf.Tensor([ 60 150], shape=(2,), dtype=int32)
tf.Tensor([50 70 90], shape=(3,), dtype=int32)


In [36]:
import tensorflow as tf
x=tf.constant([[10,20,30],[40,50,60]])
print("Original:")
print(x)
print("Sum axis=0:")
print(tf.reduce_sum(x,axis=0))
print("Sum axis=1:")
print(tf.reduce_sum(x,axis=1))
print("Mean axis=0:")
print(tf.reduce_mean(x,axis=0))
print("Mean axis=1:")
print(tf.reduce_mean(x,axis=1))

Original:
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
Sum axis=0:
tf.Tensor([50 70 90], shape=(3,), dtype=int32)
Sum axis=1:
tf.Tensor([ 60 150], shape=(2,), dtype=int32)
Mean axis=0:
tf.Tensor([25 35 45], shape=(3,), dtype=int32)
Mean axis=1:
tf.Tensor([20 50], shape=(2,), dtype=int32)


In [38]:
import tensorflow as tf
x=tf.constant([10,50,20,40,30])
result=tf.argmax(x)
print(result)
result=tf.argmin(x)
print(result)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [40]:
import tensorflow as tf
x=tf.constant([[10,50,20],[40,30,60]])
print(tf.argmax(x,axis=0))
print(tf.argmax(x,axis=1))
print(tf.argmin(x,axis=0))
print(tf.argmin(x,axis=1))

tf.Tensor([1 0 1], shape=(3,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)
tf.Tensor([0 1 0], shape=(3,), dtype=int64)
tf.Tensor([0 1], shape=(2,), dtype=int64)


In [41]:
import tensorflow as tf
x=tf.constant([30,10,50,20,40])
print(tf.sort(x))

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [42]:
import tensorflow as tf
x=tf.constant([30,10,50,20,40])
print(tf.argsort(x))

tf.Tensor([1 3 0 4 2], shape=(5,), dtype=int32)


In [43]:
import tensorflow as tf
x=tf.constant([10,25,5,40,15])
result=tf.where(x>20)
print(result)

tf.Tensor(
[[1]
 [3]], shape=(2, 1), dtype=int64)


In [44]:
import tensorflow as tf
x=tf.constant([10,25,5,40,15])
result=tf.where(x>20,x,0)
print(result)

tf.Tensor([ 0 25  0 40  0], shape=(5,), dtype=int32)


In [45]:
import tensorflow as tf
x=tf.constant([10,20,30,40])
print(x>25)
print(x<25)
print(x==20)
print(x>=30)
print(x<=20)

tf.Tensor([False False  True  True], shape=(4,), dtype=bool)
tf.Tensor([ True  True False False], shape=(4,), dtype=bool)
tf.Tensor([False  True False False], shape=(4,), dtype=bool)
tf.Tensor([False False  True  True], shape=(4,), dtype=bool)
tf.Tensor([ True  True False False], shape=(4,), dtype=bool)


In [46]:
import tensorflow as tf
a=tf.constant([10,20,30])
b=tf.constant([15,20,25])
print(tf.math.greater(a,b))
print(tf.math.less(a,b))
print(tf.math.equal(a,b))

tf.Tensor([False False  True], shape=(3,), dtype=bool)
tf.Tensor([ True False False], shape=(3,), dtype=bool)
tf.Tensor([False  True False], shape=(3,), dtype=bool)
