In [1]:
#what is a tensors
# a tensor is a multidimensional array of numbers
#scalar=0D tensor -- a single number
#[1,2,3] --vector 1D tensor
#why do we need tensors?  


In [5]:
#creating tensors in PYTORCH
#ndim tells dimensions
import torch
x=torch.tensor([1,2,3])
print(x)
print(x.ndim)
b=torch.tensor([[1,2,3],[4,5,6]])
print(b.ndim)

tensor([1, 2, 3])
1
2


In [6]:
#shape tells how many elements exist alond each dimension
x=torch.tensor([1,2,3])
b=torch.tensor([[1,2,3],[4,5,6]])
print(b.shape)

torch.Size([2, 3])


In [10]:

x=torch.tensor([1,2,3])
b=torch.tensor([[1,2,3],[4,5,6]])
print(b.size())

torch.Size([2, 3])


In [9]:
#numel tells how many elements exist 
b=torch.tensor([[1,2,3],[4,5,6]])
print(b.numel())

6


In [11]:
#tensor datatype
b=torch.tensor([[1,2,3],[4,5,6]])
print(b.dtype)


torch.int64


In [16]:
x=torch.tensor([1.,2.,3.])
print(x.dtype)
print(x.device)

torch.float32
cpu


In [20]:

v=torch.zeros(3)
print(v)
b=torch.zeros(2,3)
print(b)

tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [21]:

v=torch.ones(3)
print(v)
b=torch.ones(2,3)
print(b)

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [23]:

v=torch.rand(3)
print(v)
b=torch.rand(2,3)
print(b)

tensor([0.9361, 0.5157, 0.7780])
tensor([[0.2597, 0.5908, 0.0164],
        [0.2347, 0.5256, 0.2024]])


In [25]:

v=torch.randn(3)
print(v)
b=torch.randn(3,3)
print(b)

tensor([ 0.1969, -1.8697,  2.2371])
tensor([[-0.4298,  1.8064,  1.4995],
        [ 0.5426, -0.4458,  0.3434],
        [-0.7876, -0.6835,  2.3806]])


In [27]:
# creating IDENTY MATRIX
v=torch.eye(3)
print(v)
b=torch.eye(4)
print(b)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [30]:

v=torch.arange(3)
print(v)
b=torch.arange(0,10)
print(b)
n=torch.arange(0,10,3)
print(n)

tensor([0, 1, 2])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 3, 6, 9])


In [33]:
#evenly spaced values between two numbers
b=torch.linspace(0,5,4)
print(b)

tensor([0.0000, 1.6667, 3.3333, 5.0000])


In [36]:
torch.manual_seed(42)
torch.rand(3)

tensor([0.8823, 0.9150, 0.3829])

In [39]:
#indexing tensors
x=torch.tensor([1,2,3,4,5,6])
x[0]
x[5]

tensor(6)

In [45]:
#2D indexing
x=torch.tensor([[12,3,4,5],[2,45,89,4]])
print(x)
x[1][1]
x[1][3]
x[1,2]

tensor([[12,  3,  4,  5],
        [ 2, 45, 89,  4]])


tensor(89)

In [50]:
#slicing
x=torch.tensor([10,20,30,40,50])
x[1:4]
r=torch.tensor([[12,3,4,5],[2,45,89,4]])
print(r)
r[1:,1:2]
r[0:2,2:4]



tensor([[12,  3,  4,  5],
        [ 2, 45, 89,  4]])


tensor([[ 4,  5],
        [89,  4]])

In [52]:
#tensor operations
a=torch.tensor([1,2,34,45])
b=torch.tensor([7,8,9,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


tensor([ 8, 10, 43, 55])
tensor([-6, -6, 25, 35])
tensor([  7,  16, 306, 450])
tensor([0.1429, 0.2500, 3.7778, 4.5000])


In [53]:
#scalar operations
x=torch.tensor([1,3,4,5])
print(x+10)
print(x*10)
print(x-10)

tensor([11, 13, 14, 15])
tensor([10, 30, 40, 50])
tensor([-9, -7, -6, -5])


In [54]:
#Matrix multiplication
# here element wise multiplication (a*b) is different from the matrix multiplication (a@b) or(matmul(a,b))
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([[3,4],[4,8]])
print(a@b)

tensor([[11, 20],
        [25, 44]])


In [59]:
#Aggregation operations
x=torch.tensor([1,3,4,5])
print(x.sum())
print(x.min())
print(x.max())
print(x.std)


tensor(13)
tensor(1)
tensor(5)
<built-in method std of Tensor object at 0x7f5b9743ba20>


In [60]:
x=torch.tensor([1,3,4,5])
print(x.argmax())#index value


tensor(3)


In [69]:
x=torch.arange(1,19)
print(x)
print(x.shape)
print(x.reshape(3,6))
print(x.reshape(2,9))
print(x.reshape(2,3,3))


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
torch.Size([18])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])


In [71]:
x=torch.arange(1,9)
print(x)
print(x.view(3,3))

tensor([1, 2, 3, 4, 5, 6, 7, 8])


RuntimeError: shape '[3, 3]' is invalid for input of size 8

In [76]:
x=torch.tensor([1,2,3])
print(x.shape)
t=x.unsqueeze(0)
print(t.shape)
f=x.unsqueeze(1)
print(f.shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


In [77]:
#transpose
x=torch.tensor([[1,2,3],[4,5,6]])
print(x)
print(x.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [79]:
#CONCATENATION
a=torch.tensor([1,2])
b=torch.tensor([3,4])
print(torch.cat((a,b)))

tensor([1, 2, 3, 4])


In [80]:
#Broadcasting
x=torch.tensor([[1,2,3],[4,5,6]])
y=torch.tensor([10,20,30])
print(x+y)

tensor([[11, 22, 33],
        [14, 25, 36]])
